name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy SWA
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        working-directory: ./apps/src/azure-signalr-hubclient-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.0
          cache: 'yarn'
          cache-dependency-path: ./apps/src/azure-signalr-hubclient-web/yarn.lock

      - name: Setup Yarn v4 (Berry)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build application
        env:
          NODE_ENV: production
          VITE_APP_TITLE: "SignalR POC Web Client"
          VITE_KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
          VITE_KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
          VITE_KEYCLOAK_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          VITE_SIGNALR_HUB_URL: ${{ secrets.SIGNALR_HUB_URL }}
          VITE_SIGNALR_TRANSPORT: ${{ secrets.SIGNALR_TRANSPORT }}
          VITE_APIM_SUBSCRIPTION_KEY: ${{ secrets.APIM_SUBSCRIPTION_KEY }}
          VITE_SIGNALR_SKIP_NEGOTIATION: false

        run: yarn run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          production_branch: main
          app_location: ./apps/src/azure-signalr-hubclient-web/dist
          skip_app_build: true
